name: Release

on:
  push:
    branches:
      - experimental
    tags:
      - v*.*.*
      - v*.*.*-*

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: pnpm install
      - id: version
        uses: VdustR/semver-action@v0
      - name: Build
        run: pnpm build
      - run: pnpm pkg set version=${{ steps.version.outputs.version }}
      - run: npm publish --access public --tag ${{ steps.version.outputs.tag }}
